global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Roman Numeral Converter API
  - job_name: 'roman-numeral-api'
    static_configs:
      - targets: ['roman-numeral-converter:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s 